### ISSUE TITLE
Readme run script

### ISSUE THREAD

**Issue by gje4** [uniquelyparticular/import-moltin-to-algolia#34]
**Describe the bug**
In the read me command
Full import (run the following command):

./bin/import-moltin-to-algolia
Partial import (run the following command specifying a comma seperated list w/o spaces of entities to index):

./bin/import-moltin-to-algolia products,brands

I may be missing something but think it should be

./bin/moltin-to-alolia import

**Comment by agrohs** [comment]
Thanks @gje4. that will unfortunately require a PR and a 5 month back and forth plus wait period to get fixed (just kidding...)! I'll get that readme fixed right away and/or feel free to submit a PR w/ it fixed on your end and I'll merge right away.

**Comment by agrohs** [comment]
pushing update to it now
